# -*- coding: utf-8 -*-
"""RAG2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cpdg-_g7FZ2ogUiNeAqSVfG8fhfOjHor
"""

pip install pypdf sentence-transformers faiss-cpu transformers

from pypdf import PdfReader
from google.colab import files
import os

# Upload the PDF file
print("Please upload your PDF document.")
uploaded = files.upload()

# Assuming only one file is uploaded, get its name
if uploaded:
    pdf_filename = list(uploaded.keys())[0]
    print(f"Successfully uploaded: {pdf_filename}")
else:
    print("No file was uploaded. Please try again.")
    # If no file is uploaded, the script cannot proceed.
    # You might want to raise an error or exit here.
    # For now, we'll assign a placeholder, which will likely lead to an error.
    pdf_filename = "document.pdf" # This will likely cause a FileNotFoundError if no file was uploaded.

# Check if the file exists after upload (for robustness)
if not os.path.exists(pdf_filename):
    print(f"Error: File '{pdf_filename}' not found after upload. Please ensure you uploaded the correct file.")
else:
    reader = PdfReader(pdf_filename)

    text = ""

    for page in reader.pages:
        text += page.extract_text()

    print(text[:500])   # preview first 500 characters

chunk_size = 500
chunks = []

for i in range(0, len(text), chunk_size):
    chunks.append(text[i:i+chunk_size])

print(len(chunks))

from sentence_transformers import SentenceTransformer

embed_model = SentenceTransformer("all-MiniLM-L6-v2")

doc_embeddings = embed_model.encode(chunks)

import faiss
import numpy as np

dimension = doc_embeddings.shape[1]

index = faiss.IndexFlatL2(dimension)

index.add(np.array(doc_embeddings))

query = input("Ask a question about the PDF: ")

query_embedding = embed_model.encode([query])

k = 3

distances, indices = index.search(query_embedding, k)

retrieved_docs = [chunks[i] for i in indices[0]]

context = " ".join(retrieved_docs)

from transformers import pipeline

generator = pipeline("text-generation", model="gpt2")

prompt = f"""
Context: {context}

Question: {query}

Answer:
"""

result = generator(prompt, max_length=200)

print(result[0]["generated_text"])

